# Generated by Django 5.2 on 2025-04-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.CharField(max_length=50, unique=True)),
                ("company_name", models.CharField(max_length=100)),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_email", models.EmailField(max_length=254, unique=True)),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_user3",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
