# Generated by Django 5.2 on 2025-04-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
    ]
