# Generated by Django 5.2 on 2025-04-03 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_company_company_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["company_name"]},
        ),
        migrations.RemoveField(
            model_name="company",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="company",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="company",
            name="user3",
        ),
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                related_name="companies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
